---
- hosts: ws
  become: yes
  ignore_errors: yes
  vars_files:
    - vars.yml 
  tasks: 
    - name: Download package
      get_url:
        url: "{{ LINK_URL }}"
        dest: "{{ DESTINATION }}"
    - name: Delete main.zip
      file:
        path: "{{ DESTINATION }}"
        state: absent


