---
- hosts: ws
  become: yes
  tasks:
    - name: Install required packages
      package:
        state: present
        name: "{{ item }}"
      loop:
        - unzip
        - wget
        - httpd

    - name: Download artifacts
      get_url:
        url: https://github.com/kserge2001/resume/archive/refs/heads/main.zip
        dest: /tmp/main.zip

    - name: Unarchive zip file
      unarchive:
        src: /tmp/main.zip
        dest: /tmp
        remote_src: yes
    - name: Copy artifact to html folder
      become: true
      copy:
        src: /tmp/resume-main/
        dest: /var/www/html/
        remote_src: yes
    - name: Start Daemon
      systemd: 
        name: httpd
        state: started
        enabled: yes